from __future__ import annotations

import yaml
import agentcomos.controller.events as events
import agentcomos.controller.state as state

def generate_gm_report(run_id: str, format: str = "markdown") -> None:
    run_dir = state.get_run_dir(run_id)
    if not run_dir.exists():
        raise ValueError(f"Run {run_id} does not exist.")
        
    events.append_event(run_id, "gm.report.started", {"format": format})
    
    try:
        manifest_path = run_dir / "evidence_packet" / "manifest.yaml"
        runtime_path = run_dir / "evidence_packet" / "runtime_summary.yaml"
        delivery_path = run_dir / "delivery_packet.yaml"
        
        evidence_status = "failed"
        if manifest_path.exists():
            evidence_status = yaml.safe_load(manifest_path.read_text(encoding="utf-8")).get("status", "failed")
            
        delivery_status = "failed"
        if delivery_path.exists():
            delivery_status = yaml.safe_load(delivery_path.read_text(encoding="utf-8")).get("status", "failed")
            
        rt = {}
        if runtime_path.exists():
            rt = yaml.safe_load(runtime_path.read_text(encoding="utf-8"))
            
        oc = rt.get("opencode", {})
        hm = rt.get("hermes", {})
        wk = rt.get("worker", {})
        
        status = "completed"
        if evidence_status == "failed" or delivery_status == "failed":
            status = "failed"
        elif evidence_status == "partial" or delivery_status == "partial":
            status = "partial"

        if format == "yaml":
            report_yaml = {
                "run_id": run_id,
                "status": status,
                "delivery_status": delivery_status,
                "evidence_status": evidence_status,
                "summary": "GM Report generated from evidence.",
                "runtime_usage": {
                    "fake_opencode": oc.get("fake_opencode_used", False),
                    "real_opencode_attempted": oc.get("real_opencode_attempted", False),
                    "real_opencode_used": oc.get("real_opencode_used", False),
                    "fake_hermes": hm.get("fake_hermes_used", False),
                    "real_hermes_attempted": hm.get("real_hermes_attempted", False),
                    "real_hermes_used": hm.get("real_hermes_used", False),
                    "tmux_used": wk.get("tmux_used", False)
                },
                "artifacts": [
                    {"path": "evidence_packet/manifest.yaml", "type": "evidence"}
                ],
                "risks": [],
                "next_actions": ["Ready for review."]
            }
            path = run_dir / "gm_report.yaml"
            path.write_text(yaml.dump(report_yaml, sort_keys=False), encoding="utf-8")
        else:
            report_md = f"""# GM Report - {run_id}

## Executive Summary
Generated from evidence packet.

## Current Status
- Run ID: {run_id}
- Status: {status}
- Delivery Status: {delivery_status}
- Evidence Status: {evidence_status}

## What Was Done
Built GM report.

## Runtime Usage
- Fake OpenCode: {oc.get("fake_opencode_used", False)}
- Real OpenCode attempted: {oc.get("real_opencode_attempted", False)}
- Real OpenCode used: {oc.get("real_opencode_used", False)}
- Fake Hermes: {hm.get("fake_hermes_used", False)}
- Real Hermes attempted: {hm.get("real_hermes_attempted", False)}
- Real Hermes used: {hm.get("real_hermes_used", False)}
- tmux used: {wk.get("tmux_used", False)}

## Evidence
- `evidence_packet/manifest.yaml`
- `evidence_packet/events_summary.yaml`
- `evidence_packet/runtime_summary.yaml`
- `evidence_packet/artifact_index.yaml`
- `evidence_packet/validation_summary.yaml`

## Results
N/A

## Risks and Gaps
N/A

## Next Actions
Ready for review.

## Audit Notes
This report was automatically generated by AgentComOS GM Report Builder. It does not replace human verification.
"""
            path = run_dir / "gm_report.md"
            path.write_text(report_md, encoding="utf-8")
            
        events.append_event(run_id, "gm.report.completed", {"format": format})
    except Exception as e:
        events.append_event(run_id, "gm.report.failed", {"error": str(e)})
        raise
