from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml


FAKE_RUNTIME = "fake_hermes"
FAKE_SUMMARY = "Fake Hermes worker completed G4 validation."
FAKE_REASONING = (
    "Fake Hermes worker executed deterministic G4 validation. "
    "No real Hermes or LLM was used."
)


def load_invocation(invocation_path: Path) -> dict[str, Any]:
    if not invocation_path.exists():
        raise ValueError(f"Worker Invocation not found: {invocation_path}")
    data = yaml.safe_load(invocation_path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"Worker Invocation must be a YAML mapping: {invocation_path}")
    return data


def infer_run_id(invocation: dict[str, Any]) -> str:
    if invocation.get("run_id"):
        return str(invocation["run_id"])

    output_dir = Path(str(invocation.get("output_dir", "")))
    parts = output_dir.parts
    for index, part in enumerate(parts):
        if part == "runs" and index + 1 < len(parts):
            return parts[index + 1]
    raise ValueError("Worker Invocation must include run_id or output_dir under .agentcomos/runs/<run_id>/")


def task_id_from_invocation(invocation: dict[str, Any]) -> str:
    task = invocation.get("task")
    if not isinstance(task, dict) or not task.get("task_id"):
        raise ValueError("Worker Invocation missing task.task_id")
    return str(task["task_id"])


def required_outputs(invocation: dict[str, Any]) -> list[str]:
    outputs = invocation.get("required_outputs")
    if not isinstance(outputs, list) or not outputs:
        raise ValueError("Worker Invocation missing required_outputs")
    return [str(output) for output in outputs]


def output_dir_from_invocation(invocation: dict[str, Any]) -> Path:
    output_dir = invocation.get("output_dir")
    if not output_dir:
        raise ValueError("Worker Invocation missing output_dir")
    return Path(str(output_dir))


def write_fake_outputs(invocation_path: Path) -> dict[str, Any]:
    invocation = load_invocation(invocation_path)
    run_id = infer_run_id(invocation)
    task_id = task_id_from_invocation(invocation)
    output_dir = output_dir_from_invocation(invocation)
    outputs = required_outputs(invocation)
    output_dir.mkdir(parents=True, exist_ok=True)

    result = {
        "run_id": run_id,
        "task_id": task_id,
        "worker_runtime": FAKE_RUNTIME,
        "status": "completed",
        "real_hermes_used": False,
        "summary": FAKE_SUMMARY,
    }

    (output_dir / "DONE.md").write_text(
        "# DONE\n\n"
        "status: completed\n"
        "worker_runtime: fake_hermes\n"
        "real_hermes_used: false\n",
        encoding="utf-8",
    )
    (output_dir / "result.yaml").write_text(yaml.dump(result, sort_keys=False), encoding="utf-8")
    (output_dir / "reasoning_summary.md").write_text(f"{FAKE_REASONING}\n", encoding="utf-8")

    for name in outputs:
        path = output_dir / name
        if path.exists():
            continue
        if name.endswith(".yaml") or name.endswith(".yml"):
            path.write_text(
                yaml.dump(
                    {
                        "run_id": run_id,
                        "task_id": task_id,
                        "worker_runtime": FAKE_RUNTIME,
                        "status": "not_applicable",
                        "real_hermes_used": False,
                        "summary": "Deterministic placeholder generated by fake Hermes worker.",
                    },
                    sort_keys=False,
                ),
                encoding="utf-8",
            )
        elif name.endswith(".md"):
            path.write_text(
                "# Fake Hermes Placeholder\n\n"
                "Deterministic placeholder generated by fake Hermes worker.\n",
                encoding="utf-8",
            )
        else:
            path.write_text("fake_hermes_placeholder\n", encoding="utf-8")

    return {
        "run_id": run_id,
        "task_id": task_id,
        "output_dir": str(output_dir),
        "required_outputs": outputs,
        "worker_runtime": FAKE_RUNTIME,
        "real_hermes_used": False,
    }

